lru cache
davidnatro/fintech pull request #13
Opened 2023-11-19 09:52 UTC by davidnatro

2023-11-25 13:27 UTC, EMDavl requested changes
Не хватает тестов с проверкой работоспособности кеша

2023-11-25 13:27 UTC, EMDavl commented on src/main/java/com/fintech/fintech/service/impl/hibernate/HibernateCityServiceImpl.java
> +        this.weatherCache = Collections.synchronizedMap(new WeatherCache<>(cacheProperty));
Кмк надежнее сделать приватный конструктор в кеше и фабричный метод, который сразу будет возвращать потокобезопасный кеш

2023-11-25 13:27 UTC, EMDavl commented on src/main/java/com/fintech/fintech/data/cache/WeatherCache.java
> +        this.cacheProperty = cacheProperty;
В LRU должен соблюдаться порядок в котором элементы запрашивались, в текущий момент соблюдается порядок вставки

hint: можно поменять параметром конструктора

2023-11-25 13:27 UTC, EMDavl commented on src/main/java/com/fintech/fintech/data/entity/City.java
> +    public boolean equals(Object o) {
Можно заменить на ломбоковский `@EqualsAndHashcode` и указать там какие поля хочешь исключить

2023-11-27 17:14 UTC, davidnatro commented on src/main/java/com/fintech/fintech/data/entity/City.java
> +    public boolean equals(Object o) {
мне как-то раз ide подсветила данную аннотацию с указанием того, что она потребляет слишком много ресурсов и предложила заменить на перегруженные equals и hashcode. Возможно это было из-за вложенных объектов, уже честно не припомню, но с этого момента больше не использовал данную аннотацию.

2023-11-30 15:14 UTC, EMDavl approved these changes

2023-12-11 17:05 UTC, merged