homework 4
davidnatro/fintech pull request #6
Opened 2023-10-07 09:19 UTC by davidnatro

2023-10-10 18:37 UTC, EMDavl requested changes

2023-10-10 18:37 UTC, EMDavl commented on src/main/java/com/fintech/fintech/client/impl/WeatherClientImpl.java
> +        return restTemplate.getForObject(
Если сервис ответит с ошибкой 4хх / 5хх, то метод тоже выкинет ошибку, которая нигде не обрабатывается. Надо добавить отлов и обработку

2023-10-11 15:25 UTC, davidnatro commented on src/main/java/com/fintech/fintech/client/impl/WeatherClientImpl.java
> +        return restTemplate.getForObject(
Добавил обработку через ResponseErrorHandler + RestControllerAdvice. Изначально задумка была в том, что, как мне кажется, не все исключения следует обрабатывать, так как программа из-за них не упадет, а данные об ошибке мы получим со всей нужной информацией + в данной ситуации не требовалось никаких дополнительных действий (откатов/логирования), которые могли быть произведены в обработчике. 
Возвращаясь к информации об ошибке, я понимаю, что с таким же успехом можно просто вывести stackTrace и получить те же данные, но тогда обработка ошибки не будем ничем отличаться от ее выброса наружу, опять же, пока не требуется дополнительных действий. Является ли данное мнение ошибочным? Хотелось бы узнать best practice

2023-10-11 15:39 UTC, davidnatro commented on src/main/java/com/fintech/fintech/client/impl/WeatherClientImpl.java
> +        return restTemplate.getForObject(
к примеру, бд тоже может начать возвращать ошибки, но писать обработчики для sql exception'ов,  jdbc connection ex и остальных будто слишком громоздко. Разве не лучше полностью увидеть ошибку о том, что закончился пул коннектов? + так как это не дойдет до handler'а или advice'а spring может сам сохранить код ошибки в данные возвращаемые prometheus'у, а после это можно отобразить в grafana и сразу увидеть, что что-то идет не так

2023-10-11 17:11 UTC, EMDavl commented on src/main/java/com/fintech/fintech/client/impl/WeatherClientImpl.java
> +        return restTemplate.getForObject(
> данные об ошибке мы получим со всей нужной информацией

Результат вызова метода WeatherClient прокидывается в сервис и далее в контроллер. Возможно, обрабатывать 400 / 500 через ResponseErrorHandler действительно может быть необязательно и можно отлавливать спринговые HttpClientErrorException / HttpServerErrorException. Однако ошибку, которая прокидывается в контроллер лучше все таки обработать в RestControllerAdvice., т.к. чаще всего у нас есть какой-то фиксированный контракт ответа, возможно у нас используются какие-то специфические коды ошибок напр. не 404 а 422 при запросе ресурса и т.д. На этот контракт завязывается какая-то другая система / фронт, поэтому мы хотим полностью держать под контролем то что мы отдаем во внешний мир.

Также информация из ответа сторонней системы может быть на деле какой-то технической, которую пользователю прокидывать мы бы не хотели, а вместо этого хотели бы отправить в ответе что-то человекочитаемое (на случай если на фронт отдаем например)

Надеюсь ответил на вопрос

2023-10-11 17:13 UTC, EMDavl approved these changes

2023-10-11 17:18 UTC, davidnatro commented on src/main/java/com/fintech/fintech/client/impl/WeatherClientImpl.java
> +        return restTemplate.getForObject(
Согласен, был не прав. В рамках домашнего задания даже не задумался о фронте и ответе пользователю. Спасибо за ответ!

2023-10-11 17:21 UTC, merged